### ISSUE TITLE
Item not found when exporting a workbook/view

### ISSUE THREAD

**Issue by kulicny** [tableau/tabcmd#159] opened 2022-08-09 18:13 UTC
When executing the export command, I continually receive the Item not found error.  I'm using the same export string that I was using previously with the old tabcmd.  I know there are some differences as I had to modify by login and add some extra - to some other commands.  If this is not the place to report or ask about this let me know where to post and I will do so.

**Comment by j-hajicek** [comment] 2022-08-10 14:57
I also am having some difficulty using existing export commands with this version. It returns a PDF but doesn't apply filter.
 
  ![Capture](https://user-images.githubusercontent.com/110993722/183937025-d491df4d-69ab-4b8e-b9a9-7d498e25ee50.JPG)

**Comment by jacalata** [comment] 2022-08-10 20:30
@kulicny  - I believe I fixed that last week in the development branch, are you able to install from that to check it out? If not, I'm planning to cut another release this week. 

@j-hajicek I'll look into that as a separate issue.

**Comment by kulicny** [comment] 2022-08-11 02:41
I will check it out tomorrow and let you know. Thanks!

Ken Ulicny

On Aug 10, 2022, at 4:30 PM, Jac ***@***.***> wrote:

﻿

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@kulicny<https://github.com/kulicny> - I believe I fixed that last week in the development branch, are you able to install from that to check it out? If not, I'm planning to cut another release this week.

@j-hajicek<https://github.com/j-hajicek> I'll look into that as a separate issue.

**Comment by j-hajicek** [comment] 2022-08-25 19:45
Were you able to take a look at this?

**Comment by kulicny** [comment] 2022-08-25 20:07
My apologies.  I’m new to the github world and was not able to figure out how to pull the development branch to test it.  I was going to reach out to you but then I then had some other issues crop up that took precedence and never got back to it.  If you can tell me how to get the development branch, I will make it a priority to test and let you know.

Ken Ulicny

**Comment by j-hajicek** [comment] 2022-08-25 20:16
I will classify myself as a tester :)

I'm only on here to possibly use this version of tabcmd to satisfy the MFA requirement from Tableau

**Comment by kulicny** [comment] 2022-08-25 20:20
That is why I am here as well.  A tableau forum brought me to github and I’m hoping to use it for the exact same reasons as tableau is requiring MFA but has not provided a solution to use the tokens.  I was able to connect to tableau but was not able to pull a report.

Ken Ulicny

**Comment by jacalata** [comment] 2022-08-27 15:37
Sorry,  I forgot to add instructions for installing the development branch. Run this command:
pip install git+https://github.com/tableau/tabcmd.git@development

This is indeed the right place for help with tabcmd, and it is intended to be your MFA solution!

**Comment by kulicny** [comment] 2022-08-27 18:51
Excellent thanks!  I’ll check it out.

Ken Ulicny

On Aug 27, 2022, at 11:37 AM, Jac ***@***.***> wrote:

﻿

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Sorry, I forgot to add instructions for installing the development branch. Run this command:
pip install ***@***.***

This is indeed the right place for help with tabcmd, and it is intended to be your MFA solution!

**Comment by kulicny** [comment] 2022-08-29 16:46
I ran the command below and it was installed.  I’m not sure how to execute the tabcmd to test the functionality as I don’t see a tabcmd.exe anywhere in the tar file.  I’m new to all this so I apologize in advance.

Ken Ulicny

**Comment by jacalata** [comment] 2022-08-29 16:50
In the same directory, try
`python -m tabcmd login ...`

**Comment by kulicny** [comment] 2022-08-29 17:15
Thank you.  I will play around with it and let you know if I’m successful with retrieving a view.

Ken Ulicny

**Comment by kulicny** [comment] 2022-08-29 18:20
I was able to execute the command.  I’m using the same command below that I use with regular tabcmd and it continues to give me the Item not found error.  Perhaps I need to send the command differently but for now, that is the result I’m receiving.


c:\tabcmd\Command Line Utility\NewTabCmd>python -m tabcmd export "PremiumRegister2/PremiumRegister?:refresh=yes" --pdf --pagelayout portrait --pagesize legal --width 1920 --filename "premregistertest"
Read the Tableau Server password from FILE
Creating new session
=====   Server: https://prod-useast-a.online.tableau.com
=====   Username: ***@***.******@***.***>
Tableau Server Site: westcongressinsurance
Connecting to the server...
Succeeded
Requesting ''PremiumRegister2/PremiumRegister?:refresh=yes'' from the server...
Item not found

Ken Ulicny

**Comment by jacalata** [comment] 2022-08-29 18:24
Could you re-run it and add the parameter "logging-level=DEBUG"?

**Comment by kulicny** [comment] 2022-08-29 18:35
I’ve put that in a few different places for the command I’m running, but it doesn’t like it.  Where should that command be placed?


Ken Ulicny

**Comment by jacalata** [comment] 2022-08-29 18:45
Here's how I run it:
`c:\tabcmd>python -m tabcmd get /workbooks/Regional.twbx --logging-level=DEBUG`

**Comment by mosuarez1971** [comment] 2022-09-02 19:53
Hello, when exporting a view to csv, I am getting this INFO message and the output file is empty. It does generate some content if I export to PDF, but I need the CSV version of the view. Were you aware of the issue?

INFO:  a bytes-like object is required, not 'generator'

Here is the command used:

tabcmd export "workbook_name/view_name" --csv -f "filename"

Thanks.

**Comment by mosuarez1971** [comment] 2022-09-02 20:04
Additional details with the DEBUG option:

DEBUG: ExportCommand: 22: Requesting ''workbook/view'' from the server...
DEBUG: ExportCommand: 147: Found attachment: c:\<filepath>.csv
DEBUG: ExportCommand: 45: Error saving to file
DEBUG: ExportCommand: 53: a bytes-like object is required, not 'generator'

**Comment by jacalata** [comment] 2022-09-02 22:25
This looks like a bug that we fixed in the development version already -
are you able to try running from that branch?

**Comment by mosuarez1971** [comment] 2022-09-02 22:45
I installed and built the development version, but I am not sure where the new tabcmd.exe file was installed to test it. 

Building wheels for collected packages: tabcmd, tableauserverclient
  Building wheel for tabcmd (pyproject.toml) ... done
  Created wheel for tabcmd: filename=tabcmd-2.0.7.dev1-py3-none-any.whl size=1237188 sha256=28f7fdae296bb32694758c91119fb3b3ee5cd7ec61ba0d66e70ae90a23a9743c
  Stored in directory: C:\Users\admin\AppData\Local\Temp\pip-ephem-wheel-cache-l_g_uc_j\wheels\f5\75\fd\8193a3eb1243824c2048be79a7ffef0498ebb8f9d793c6a4fd
  Building wheel for tableauserverclient (pyproject.toml) ... done
  Created wheel for tableauserverclient: filename=tableauserverclient-0.19.0-py2.py3-none-any.whl size=121863 sha256=2514bdb0d8f92bd0cb5fc80205945621e6e285b718ce241e4d26dd2c63dd3e71
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\2b\6a\7f\df5ea7ee85bbabf3f81d93a8666ae7567c8df1f4fd37a8497c
Successfully built tabcmd tableauserverclient
Installing collected packages: polling2, urllib3, idna, defusedxml, charset-normalizer, certifi, requests, tableauserverclient, tabcmd
Successfully installed certifi-2022.6.15 charset-normalizer-2.1.1 defusedxml-0.7.1 idna-3.3 polling2-0.5.0 requests-2.28.1 tabcmd-2.0.7.dev1 tableauserverclient-0.19.0 urllib3-1.26.12

**Comment by jacalata** [comment] 2022-09-02 22:59
Try running it directly with python -m tabcmd

**Comment by mosuarez1971** [comment] 2022-09-02 23:02
It worked. Thanks!

**Comment by jacalata** [comment] 2022-09-02 23:07
Excellent! I’ll add some more info to the readme 😀

**Comment by kulicny** [comment] 2022-09-07 14:16
Let me know if you’d like me to do any further tests.  I’d be happy to assist.

Ken Ulicny

From: Ken Ulicny
Sent: Monday, August 29, 2022 2:56 PM
To: tableau/tabcmd ***@***.***>; tableau/tabcmd ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [tableau/tabcmd] Item not found when exporting a workbook/view (Issue #159)

Thanks.  Forgot the second -

Anyway, here is the output, if you are interested.  I would not have expected to see /sheets/ in there.


DEBUG: ExportCommand: 132: Requesting ''PremiumRegister2/PremiumRegister?:refresh=yes'' from the server...
DEBUG: ExportCommand: 72: ['PremiumRegister2/sheets/PremiumRegister?:refresh=yes', 'PremiumRegister2']
DEBUG: ExportCommand: 22: Requesting ''PremiumRegister2/sheets/PremiumRegister?:refresh=yes'' from the server...
DEBUG: ExportCommand: 36: Item not found
Ken Ulicny

**Comment by jacalata** [comment] 2022-09-09 20:48
I realized that actually the problem is the ?:refresh=yes parameter, which wasn't being stripped properly. I believe I have now fixed this in https://github.com/tableau/tabcmd/pull/175

**Comment by kulicny** [comment] 2022-09-13 18:12
I pulled the development version, and it shows I’m running 2.0.7.  Assuming that is the corrected version, I am able to connect to tableaus using the token in lieu of a password and I’m also now able to generate a pdf report.  I’m also able to pass parameters to restrict the report output.

Let me know if you need me to test anything else on this.

Ken Ulicny

**Comment by jacalata** [comment] 2022-09-19 06:46
That sounds like it's fixed, thanks so much for following up! I'll close this now.

**Closed by jacalata** 2022-09-19 06:46 UTC
Labels: bug

**Comment by kulicny** [comment] 2022-10-11 08:24
Thanks.  Forgot the second -

Anyway, here is the output, if you are interested.  I would not have expected to see /sheets/ in there.


DEBUG: ExportCommand: 132: Requesting ''PremiumRegister2/PremiumRegister?:refresh=yes'' from the server...
DEBUG: ExportCommand: 72: ['PremiumRegister2/sheets/PremiumRegister?:refresh=yes', 'PremiumRegister2']
DEBUG: ExportCommand: 22: Requesting ''PremiumRegister2/sheets/PremiumRegister?:refresh=yes'' from the server...
DEBUG: ExportCommand: 36: Item not found
Ken Ulicny
